class FinancialReporting:
    """Represents financial reporting for the mall.

    Attributes:
        total_revenue (float): The total income generated by the mall.
        total_sales (float): The total sales amount made within the mall.
        sales_date (str): The date of sales recording.
    """

    def __init__(self, total_revenue: float, total_sales: float, sales_date: str):
        """Initializes a FinancialReporting object."""
        self.total_revenue = total_revenue
        self.total_sales = total_sales
        self.sales_date = sales_date

    def get_sales_date(self) -> str:
        """Retrieves the sales date."""
        return self.sales_date

    def get_revenue(self) -> float:
        """Returns the total revenue."""
        return self.total_revenue

    def get_sales(self) -> float:
        """Returns the total sales."""
        return self.total_sales
